name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: go version
      - run: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: go version
         